services:
  app:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8009:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRES_USER=testapp
      - POSTGRES_PASSWORD=testapp
      - POSTGRES_DB=widget_dev

  redis:
    image: redis:7
    stop_signal: SIGTERM
    container_name: redis
    ports:
      - "6379:6379"
    expose:
      - 6379
    volumes:
      - redis_data:/data
    # command: ["redis-server", "--appendonly", "yes", "--requirepass", "yourpassword"] # comment out auth
    command: ["redis-server", "--save", "", "--appendonly", "no"]

volumes:
  postgres_data:
  redis_data:
