# Generated by Django 5.0.7 on 2025-01-07 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shapes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shape",
            name="face_count",
            field=models.IntegerField(),
        ),
    ]
